version: '27.1.1'
# services:
#   web:
#     build: .
#     ports:
#       - "3000:3000"
#     restart: always
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:3000"]
#       interval: 30s
#       timeout: 10s
#       retries: always

services:
  web:
    build: .
    ports:
      - "3000:3000"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3  # ✅ Fix: Use an integer value instead of "always"
